/**
 * ── 🔀🚨⭐⭐⭐ ONE PIN TABLE. THE GUARD THAT FAILS WHEN A SECOND ONE APPEARS ──
 *
 * Roman, 2026-09-18: *"these switches when a provider fucks up, we need to have
 * a process where the cheapest next one at that current moment goes through,
 * smoothly."* The mechanism behind the complaint is not the switching logic —
 * it is that **a hand-typed pin cannot know the ground moved**, and this repo
 * had five copies of it.
 *
 * `model.mjs` wrote the post-mortem of the first instance in its own words:
 * *"this one stale string was quietly overriding the cheaper route it was meant
 * to describe."* `rate-card.mjs` opens by naming the class: *"one mistake
 * copied eight times, and a copy has no way to know it is stale."*
 *
 * ── ⚠️⚠️ WHAT WAS ACTUALLY THERE ON 2026-09-18, BEFORE THIS FILE ────────────
 *
 *     acuvo-code/lib/model.mjs        table + DEFAULT_PROVIDER_ORDER   current
 *     acuvo-code/lib/plan.mjs         four retyped provider names      current
 *     acuvo-gateway/lib/handler.mjs   table + PINNED_PROVIDERS         STALE, guard RED
 *     console/lib/provider-pin.ts     table                            current
 *     console/vendor-agent/acuvo.mjs  the SHIPPED BUNDLE               STALE, and it RUNS
 *
 * ⭐ THE FIRST THREE NOW IMPORT `lib/provider-pin.mjs` and cannot drift by
 * construction. The console mirror cannot import it (a Next app pulling a
 * sibling package's `.mjs` breaks its Vercel build trace — the constraint
 * `rate-card.mjs` documents) so it stays a copy, and the bundle is generated.
 * This file is what stops a SIXTH appearing.
 *
 * ⚠️ AND IT SCANS THE TREE RATHER THAN A LIST OF FILES I THOUGHT OF. A guard
 * that checks the copies it already knows about cannot see the copy somebody
 * adds tomorrow, which is precisely how the gateway's stayed wrong.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PROVIDER_PIN_BY_MODEL, DEFAULT_PROVIDER_ORDER } from '../lib/provider-pin.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');

/** Directories with no source of ours in them. `.next*` is matched by prefix. */
const SKIP_DIRS = new Set([
  'node_modules', '.git', '.claude', 'dist', 'coverage', '.turbo', '.vercel',
  'build', 'out', '.cache', 'public', 'content-vault', '.zz-board', '.board-shots',
]);

/**
 * A pin table declaration: a model id mapped to a frozen array of names.
 * ⚠️ NOT anchored to one vendor prefix — a future chain leg from another vendor
 * is exactly the copy this must catch.
 */
const TABLE_RE = /'[a-z0-9-]+\/[a-zA-Z0-9._-]+':\s*Object\.freeze\(\[\s*'/;

function sourceFilesUnder(dir, out = []) {
  let entries;
  try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    if (e.isDirectory()) {
      if (SKIP_DIRS.has(e.name) || e.name.startsWith('.next')) continue;
      sourceFilesUnder(join(dir, e.name), out);
    } else if (/\.(mjs|cjs|js|ts|tsx|mts)$/.test(e.name)) {
      out.push(join(dir, e.name));
    }
  }
  return out;
}

const posix = (p) => relative(REPO, p).split(sep).join('/');

/**
 * ⭐ THE REGISTER. Every file allowed to contain a pin table, and WHY it is not
 * an import. A new entry here is a decision someone has to write a reason for.
 */
const ALLOWED = new Map([
  ['acuvo-code/lib/provider-pin.mjs', 'THE source. Everything else derives from it.'],
  ['console/lib/provider-pin.ts', 'A Next app cannot import a sibling package .mjs without breaking its Vercel build trace. Held by console/lib/provider-pin.test.ts and acuvo-gateway/test/pin-drift.test.mjs.'],
  ['console/vendor-agent/acuvo.mjs', 'GENERATED by acuvo-code/scripts/bundle.mjs. Never hand-edited — see the staleness test at the foot of this file.'],
]);

/** Test fixtures quote the table as TEXT; that is an assertion, not a copy. */
const QUOTES_NOT_COPIES = /\.test\.(mjs|ts|tsx)$/;

test('🔀⭐⭐⭐ exactly one hand-written provider pin table exists in the repo', () => {
  const files = sourceFilesUnder(REPO);
  assert.ok(files.length > 500, `the scan found only ${files.length} files — it is looking at the wrong tree`);

  const found = files
    .filter((f) => TABLE_RE.test(readFileSync(f, 'utf8')))
    .map(posix)
    .filter((p) => !QUOTES_NOT_COPIES.test(p));

  assert.ok(
    found.includes('acuvo-code/lib/provider-pin.mjs'),
    'the scan cannot see the SOURCE table — the pattern is wrong and this test proves nothing',
  );

  const strays = found.filter((p) => !ALLOWED.has(p));
  assert.deepEqual(
    strays, [],
    'a second copy of the provider pin table has appeared:\n  ' + strays.join('\n  ')
    + '\n\nImport it from acuvo-code/lib/provider-pin.mjs. If an import is genuinely'
    + ' impossible (a Next runtime module, a generated bundle), add the path to ALLOWED'
    + ' WITH the reason and wire a drift guard — a copy nobody compares is how'
    + ' acuvo-gateway spent eight days pinned to a delisted endpoint.',
  );
});

test('⚠️⚠️ the primary is DERIVED, so the string that went stale cannot exist again', () => {
  const src = readFileSync(join(REPO, 'acuvo-code', 'lib', 'provider-pin.mjs'), 'utf8');
  /**
   * ⚠️ THE SUBJECT IS THE ASSIGNMENT, NOT THE NAME. Asserting
   * `DEFAULT_PROVIDER_ORDER === 'Relace'` would be a fourth copy of the very
   * string this is about, and it would go red on Roman's next repin — the trap
   * `pin-drift.test.mjs` already learned once with `'StreamLake'`.
   */
  assert.match(
    src, /export const DEFAULT_PROVIDER_ORDER = PROVIDER_PIN_BY_MODEL\[/,
    'DEFAULT_PROVIDER_ORDER is a literal again — that is the exact line that stayed "StreamLake" for weeks',
  );
  assert.equal(
    DEFAULT_PROVIDER_ORDER,
    PROVIDER_PIN_BY_MODEL['deepseek/deepseek-v4-flash-0731'][0],
    'the default order is not the pinned primary',
  );
});

test('⚠️ no other module re-declares the default order as a literal', () => {
  const files = sourceFilesUnder(REPO).filter((f) => !QUOTES_NOT_COPIES.test(posix(f)));
  const literal = /(?:export\s+)?const\s+DEFAULT_PROVIDER_ORDER\s*=\s*['"]/;
  const strays = files.filter((f) => literal.test(readFileSync(f, 'utf8'))).map(posix);
  /**
   * ⚠️ THE BUNDLE IS THE ONE EXPECTED HIT and it is a generated artefact, not a
   * hand-typed copy. It is named rather than pattern-skipped so that the day it
   * is regenerated and the line disappears, this list shrinks visibly.
   */
  assert.deepEqual(
    strays.filter((p) => p !== 'console/vendor-agent/acuvo.mjs'), [],
    'a hand-typed DEFAULT_PROVIDER_ORDER is back:\n  ' + strays.join('\n  '),
  );
});

/**
 * ── 🚨⭐⭐ THE SHIPPED BUNDLE IS STALE, AND IT IS THE COPY THAT ACTUALLY RUNS ─
 *
 * `console/vendor-agent/acuvo.mjs` is a generated bundle of this package, staged
 * into the builder's sandbox by `console/lib/agent-on-machine.ts` and traced
 * into eight API routes by `console/next.config.mjs`. It was last regenerated on
 * **2026-09-07** and still carries the pre-2026-09-10 pin:
 *
 *     bundle    DEFAULT_PROVIDER_ORDER 'DeepInfra'   flash ['DeepInfra','Ambient','Relace']
 *     source    DEFAULT_PROVIDER_ORDER 'Relace'      flash ['Relace','Makora','OpenInference','DeepInfra']
 *
 * ⚠️ `Ambient` IS DELISTED — it does not serve the model at all (read off the
 * live endpoint feed 2026-09-18, and `model.mjs` `CACHE_MEASURED` already says
 * so). So every sandbox build asks for a dead endpoint as its second choice and
 * leads with the one that 429'd every build on 2026-09-09.
 *
 * ⛔ NOT FIXED HERE, DELIBERATELY. Regenerating ships eleven days of unrelated
 * CLI change into the customer-facing builder, and this machine cannot run a
 * build to verify it (the OpenRouter catalogue hangs behind the firewall).
 * `npm run bundle` is the fix and it takes one command; it wants a lane that can
 * open the product afterwards. Costed in DECISION-provider-pins-2026-09-18.md.
 *
 * ⭐ SO THIS ASSERTS THE PROPERTY THAT IS ACTUALLY HOLDABLE: the bundle is
 * either CURRENT, or it is the exact stale artefact we measured. Any third value
 * means someone hand-edited a generated file, or regenerated it half way.
 */
test('🚨 the shipped bundle is either current or the known-stale artefact — never hand-edited', () => {
  const bundle = readFileSync(join(REPO, 'console', 'vendor-agent', 'acuvo.mjs'), 'utf8');
  const m = bundle.match(/const DEFAULT_PROVIDER_ORDER = '([^']*)'/);
  const row = bundle.match(/'deepseek\/deepseek-v4-flash-0731': Object\.freeze\(\[([^\]]*)\]\)/);

  if (!m && !row) {
    /** A regenerated bundle derives the default, so the literal is simply gone. */
    assert.ok(
      bundle.includes("PROVIDER_PIN_BY_MODEL[PINNED_PRIMARY_MODEL][0]"),
      'the bundle has neither the old literal nor the new derivation — it is not a bundle of this package',
    );
    return;
  }

  assert.ok(row, 'the bundle has a DEFAULT_PROVIDER_ORDER but no pin table — half a regeneration');
  const order = row[1].split(',').map((s) => s.trim().replace(/^'|'$/g, '')).filter(Boolean);
  const live = [...PROVIDER_PIN_BY_MODEL['deepseek/deepseek-v4-flash-0731']];

  if (m[1] === DEFAULT_PROVIDER_ORDER) {
    assert.deepEqual(order, live, 'the bundle was regenerated but its table disagrees with the source');
    return;
  }

  /** The measured stale artefact, 2026-09-07. Anything else is a hand edit. */
  assert.equal(m[1], 'DeepInfra', 'the bundle is neither current nor the stale artefact we measured — it was edited by hand');
  assert.deepEqual(
    order, ['DeepInfra', 'Ambient', 'Relace'],
    'the bundle is neither current nor the stale artefact we measured — it was edited by hand',
  );
});
